(() => {
  const game = n3onGame, wait = ms => new Promise(resolve => setTimeout(resolve, ms));
  const report = globalThis.__n3onLayoutAudit = { running: true, cases: [], errors: [], screenshots: [] };
  const check = (ok, label, detail) => { report.cases.push({ ok: !!ok, label, detail }); if (!ok) throw Error(label); };
  const until = async (fn, label) => { const start = performance.now(); while (!fn()) { if (performance.now() - start > 25000) throw Error(label); await wait(40); } };
  const all = scene => { const out = []; const visit = o => { out.push(o); o.list?.forEach(visit); }; scene.children.list.forEach(visit); return out; };
  let arena, originalUpdate;
  const originalSize = { width: game.scale.width, height: game.scale.height };
  const parent = game.scale.parent, parentStyle = { width: parent.style.width, height: parent.style.height };
  const resize = (width, height) => { parent.style.width = `${width}px`; parent.style.height = `${height}px`; game.scale.resize(width, height); game.scale.refresh(); };
  const oldPads = Object.getOwnPropertyDescriptor(navigator, 'getGamepads');
  report.promise = (async () => {
    try {
      await until(() => game.scene.getScene('arena'), 'Arena registered');
      const liveModule = path => performance.getEntriesByType('resource').findLast(e => e.name.includes(path + '?t='))?.name ?? path;
      const { SaveSystem } = await import(liveModule('/src/game/systems/SaveSystem.ts'));
      const { PlayerProfileStore } = await import(liveModule('/src/game/state/PlayerProfileStore.ts'));
      const { WeeklyCompletionTracker } = await import('/src/game/progression/WeeklyCompletionTracker.ts');
      const { TUTORIAL_SEQUENCES } = await import('/src/game/tutorial/TutorialRegistry.ts');
      SaveSystem.createProfile('HUD information ' + Date.now().toString().slice(-6));
      SaveSystem.setSettings({ hud: { ...SaveSystem.get().settings.hud, tacticalInformation: true, tacticalTextSize: 'medium' } });
      SaveSystem.updateTutorialProgress(p => { p.firstRunStage = 'complete'; p.firstRunWelcomePending = false; p.completedSequences = TUTORIAL_SEQUENCES.map(s => s.id); });
      SaveSystem.getWeeklyOperations();
      for (const s of game.scene.getScenes(false)) if (s.sys.isActive() || s.sys.isPaused() || s.sys.isSleeping()) game.scene.stop(s.scene.key);
      game.scene.start('arena', { baseSeed: 550055, round: 68, protocol: 'overdrive', objectiveMode: 'open', runStartedAt: Date.now(), modsEarned: [], modFocus: null, contract: null });
      arena = game.scene.getScene('arena');
      await until(() => arena.roundRuntime?.phase === 'active', 'Arena active');
      arena.player.invulnUntil = Infinity; arena.pointerLockInitialGate = false;
      arena.playerInput.adoptDevice('gamepad');
      if (arena.state.state === 'Paused') arena.state.set('PrePlant');
      originalUpdate = arena.sys.sceneUpdate; arena.sys.sceneUpdate = () => {}; arena.physics.pause();
      arena.updateHud(arena.time.now);
      let info = arena.hudInformation;
      info.clear();
      const save = PlayerProfileStore.getActiveSave();
      const baseline = SaveSystem.previewWeeklyOperations();
      const objective = baseline.snapshot.regular.objectives.find(o => o.statKey === 'enemiesDestroyed');
      check(!!objective, 'Fixture rotation has combat kill objective');
      save.progress.enemiesDestroyed = baseline.state.baselines.enemiesDestroyed + objective.target - 1;
      const before = SaveSystem.previewWeeklyOperations();
      arena.weeklyObservationState = before.state; arena.weeklyCompletionTracker = new WeeklyCompletionTracker(before.snapshot);
      arena.pendingProgressEnemyKills = 0; arena.nextWeeklyCheckAt = 0;
      const savedKills = save.progress.enemiesDestroyed;
      const victim = arena.spawnEnemy('grunt', false);
      arena.sys.sceneUpdate = originalUpdate; arena.physics.resume(); victim.takeDamage(100000, 'weapon');
      await until(() => info.queue.active?.heading === 'WEEKLY CHALLENGE COMPLETE', 'Live combat reports weekly completion');
      check(arena.roundRuntime.phase === 'active' && arena.state.state !== 'Paused' && !arena.physics.world.isPaused, 'Weekly notice appears while ordinary combat simulation runs');
      arena.sys.sceneUpdate = () => {}; arena.physics.pause(); info.update(220);
      check(info.queue.active?.heading === 'WEEKLY CHALLENGE COMPLETE', 'Actual combat death immediately reports weekly completion');
      check(save.progress.enemiesDestroyed === savedKills && arena.pendingProgressEnemyKills === 1, 'Completion preserves batched durability and avoids per-kill save mutation');
      check(!/mod|\+\d/i.test(info.queue.active.secondary), 'Weekly objective toast does not invent a reward or include Mod presentation');
      const count = info.queue.pending.length; arena.updateWeeklyCompletion(arena.time.now + 300);
      check(info.queue.pending.length === count, 'Weekly completion is reported once');
      report.screenshots.push({ label: 'weekly', png: await new Promise(r => game.renderer.snapshot(img => r(img.src))) });
      info.clear();
      const panel = info.panel, roots = all(arena).length, canvases = Phaser.Display.Canvas.CanvasPool.pool.filter(e => e.parent?.scene === arena).length;
      for (const [heading, priority] of [['first', 0], ['second', 0], ['critical', 4], ['third', 0]]) info.notify({ category: 'system', heading, priority });
      info.update(0); check(info.queue.active.heading === 'critical', 'Queued critical notice has precedence');
      info.update(3000); check(info.queue.active.heading === 'first', 'Equal priority retains FIFO order');
      info.update(3000); check(info.queue.active.heading === 'second', 'Queue advances without overlapping panels');
      for (let i = 0; i < 100; i++) info.notify({ category: 'system', heading: 'repeat' });
      check(info.queue.pending.filter(n => n.heading === 'repeat').length === 1, 'Burst repetition coalesces');
      check(info.panel === panel && all(arena).length === roots && Phaser.Display.Canvas.CanvasPool.pool.filter(e => e.parent?.scene === arena).length === canvases, 'Notification bursts reuse the same panel and Text canvases');
      const pending = info.queue.pending.length; arena.showModBanner('COUNTERMEASURE ARRAY // 2 REMAINING');
      check(info.queue.pending.length === pending && arena.modBannerText.text.includes('COUNTERMEASURE'), 'Mod combat presentation remains outside unified queue');
      info.clear();
      const ctrl = arena.arcadeController;
      check(ctrl.force('neon-circuit'), 'Real Arcade event begins');
      info.update(0); check(info.queue.active?.category === 'arcade', 'Arcade start uses shared panel');
      ctrl.resolveActive({ success: true, reason: 'completed' });
      check(info.queue.pending.some(n => n.category === 'success'), 'Arcade success uses shared queue');
      info.clear(); check(ctrl.force('hot-package'), 'Second real Arcade event begins');
      ctrl.resolveActive({ success: false, reason: 'expired' });
      check(info.queue.pending.some(n => n.category === 'failure'), 'Arcade failure uses shared queue');
      info.clear(); check(ctrl.force('redline'), 'Redline activates');
      ctrl.active.visuals.announce('CRITICAL REDLINE / ENERGY OVERCLOCK', 0);
      info.update(0); check(info.queue.active?.category === 'redline', 'Critical Redline retains its category accent');
      check(!all(arena).some(o => o.type === 'Text' && o !== info.message && o.text === 'CRITICAL REDLINE / ENERGY OVERCLOCK'), 'No independent Redline notification text overlaps panel');
      ctrl.stop('round-ended'); info.clear();
      const laser = arena.laserSecurity, bomblet = arena.bombletHazard, gas = arena.gasHazard;
      laser.update(laser.createdAt + 7300, 0, arena.player, []);
      bomblet.forceStrikeForDevelopment(arena.time.now); bomblet.update(arena.time.now + 250, arena.player, [], false);
      gas.finishPhase(arena.time.now); gas.recoveryUntil = arena.time.now + 4500; gas.update(arena.time.now, arena.player);
      check(/\d\.\ds/.test(laser.warningText.text), 'Laser telegraph retains live countdown');
      check(/\d\.\ds/.test(bomblet.warningText.text), 'Bomblet drop retains live countdown');
      check(/LASER GRID RESET/.test(gas.warningText.text), 'Laser reactivation remains live tactical state');
      const oldLaser = laser.warningText.text;
      laser.update(laser.createdAt + 7800, 0, arena.player, []);
      check(laser.warningText.text !== oldLaser, 'Countdown updates independently of queued notices');
      const core = [arena.hud.healthValue, arena.hud.energyValue, arena.hud.objectiveText, arena.hud.objectiveTimerText];
      const coreBefore = core.map(o => ({ text: o.text, visible: o.visible }));
      const settings = SaveSystem.get().settings.hud;
      info.applySettings({ ...settings, tacticalInformation: false });
      check([laser, bomblet, gas].every(h => !h.warningText.visible), 'Tactical OFF hides auxiliary hazard feed');
      check(JSON.stringify(core.map(o => ({ text: o.text, visible: o.visible }))) === JSON.stringify(coreBefore), 'Core health, energy and bomb objective are unaffected');
      const anomaly = arena.anomalyController; check(anomaly.force(), 'Anomaly discovery activates');
      anomaly.handleEnemyKilled(arena.player.x, arena.player.y);
      info.update(0);
      check(info.eventStates.get('anomaly')?.heading === 'ANOMALY SIGNAL CHARGING' && info.panel.visible, 'Anomaly charging stays in shared panel with tactical OFF');
      check(!info.rows.has('anomaly'), 'No separate anomaly tactical row remains');
      anomaly.forceCharge(); info.update(0);
      check(info.eventStates.get('anomaly')?.heading === 'ANOMALY AVAILABLE', 'Paid entry availability uses the same event slot');
      check(info.eventStates.get('anomaly').message.includes(String(anomaly.cost)) && anomaly.cost >= 35 && anomaly.cost <= 90, 'Anomaly live prompt keeps authoritative entry cost');
      check(ctrl.force('hot-package'), 'Arcade and anomaly coexist');
      info.update(0);
      check(info.eventLines.filter(t => t.visible).length === 2, 'Both live event states remain visible during a queued toast');
      check(info.eventLines.every(t => t.parentContainer === panel), 'Live event rows belong to the single shared panel');
      const flux = arena.fluxCores;
      flux.laserSuppressedUntil = arena.time.now + 8000; flux.updateSuppressionPresentation(arena.time.now);
      check(/LASERS OFF|GRID REBOOT/.test(flux.warningText.text), 'Flux laser-disable countdown remains in tactical feed');
      const within = object => { const b = object.getBounds(), z = arena.cameras.main.zoom, w = game.scale.width, h = game.scale.height;
        return { left: w / 2 + (b.left - w / 2) * z, right: w / 2 + (b.right - w / 2) * z, top: h / 2 + (b.top - h / 2) * z, bottom: h / 2 + (b.bottom - h / 2) * z }; };
      for (const [width, height] of [[1552, 903], [1280, 720], [960, 600]]) {
        resize(width, height); await wait(80);
        check(game.scale.width === width && game.scale.height === height, `Actual canvas resized to ${width}x${height}`);
        for (const size of ['small', 'medium', 'large']) {
          info.applySettings({ ...settings, tacticalInformation: true, tacticalTextSize: size }); info.update(0);
          const bounds = [...info.rows.values()].map(r => within(r.text));
          check(bounds.every(b => b.left >= 20 && b.right <= width - 20 && b.top > within(panel).bottom && b.bottom < height - 120), `Tactical ${size} inside separate safe region at ${width}x${height}`, { bounds, panel: within(panel) });
          check(bounds.every((b, i) => bounds.every((a, j) => i === j || b.left >= a.right || b.right <= a.left || b.top >= a.bottom || b.bottom <= a.top)), `Tactical ${size} rows do not overlap at ${width}x${height}`);
        }
      }
      await wait(1500); info.clear();
      info.notify({ category: 'anomaly', heading: 'ANOMALY DETECTED', message: 'SKY BREACH', secondary: 'Access available after this encounter.' });
      info.update(0); info.update(220);
      report.screenshots.push({ label: 'compact-large-tactical', png: await new Promise(r => game.renderer.snapshot(img => r(img.src))) });
      info.update(7000);
      check(info.panel.visible && info.eventStates.size === 2, 'Live event state survives temporary notice expiration');
      ctrl.stop('round-ended'); anomaly.stop('round-ended'); info.update(0);
      check(info.eventStates.size === 0, 'Event retirement removes both live slots');
      info.clear();
      // Exercise actual Options controls and the existing shared gamepad resolver.
      game.scene.pause('arena'); arena.scene.launch('options', { returnScene: 'arena', resumeGameplay: true }); await wait(350);
      let options = game.scene.getScene('options'); options.selectTab('interface'); options.scrollActiveTab(10000); await wait(80);
      const toggle = all(options).find(o => o.type === 'Container' && /^TACTICAL INFORMATION:/.test(o.getByName('button-label')?.text ?? ''));
      check(!!toggle, 'Tactical option is exposed and scrollable');
      toggle.getByName('button-hit').emit('pointerdown', { isDown: true, id: 0 });
      check(!SaveSystem.get().settings.hud.tacticalInformation, 'Mouse toggle persists Tactical OFF');
      const module = performance.getEntriesByType('resource').findLast(e => e.name.includes('/src/game/input/UiNavigationController.ts?t='))?.name ?? '/src/game/input/UiNavigationController.ts';
      const { UiNavigationController } = await import(module);
      const pad = { id: 'Xbox 360 Controller (XInput STANDARD GAMEPAD)', index: 0, connected: true, mapping: 'standard', axes: [0, 0, 0, 0], buttons: Array.from({ length: 17 }, () => ({ pressed: false, touched: false, value: 0 })), timestamp: 0 };
      Object.defineProperty(navigator, 'getGamepads', { configurable: true, value: () => { pad.timestamp = performance.now(); return [pad]; } });
      const press = async button => { pad.buttons[button] = { pressed: true, touched: true, value: 1 }; await wait(100); pad.buttons[button] = { pressed: false, touched: false, value: 0 }; await wait(100); };
      await wait(120); const nav = UiNavigationController.get().layers.find(l => l.id === 'phaser:options');
      const sizeId = [...nav.labels].find(([, label]) => label === 'TACTICAL TEXT SIZE')?.[0];
      check(!!sizeId && nav.manager.focus(sizeId), 'Controller can focus tactical size');
      await press(15); check(SaveSystem.get().settings.hud.tacticalTextSize === 'large', 'Controller Right selects Large');
      await press(14); check(SaveSystem.get().settings.hud.tacticalTextSize === 'medium', 'Controller Left selects Medium');
      await press(14); check(SaveSystem.get().settings.hud.tacticalTextSize === 'small', 'Controller Left selects Small');
      await press(15); await press(15);
      resize(1280, 720); await wait(450); options = game.scene.getScene('options');
      check(options.activeTab === 'interface' && SaveSystem.get().settings.hud.tacticalTextSize === 'large', 'Open Options resize preserves tab and setting');
      options.scrollActiveTab(10000);
      report.screenshots.push({ label: 'options-tactical', png: await new Promise(r => game.renderer.snapshot(img => r(img.src))) });
      UiNavigationController.get().layers.find(l => l.id === 'phaser:options').back(); await wait(350);
      check(!game.scene.isActive('options') && info.settings.tacticalInformation === false && info.settings.tacticalTextSize === 'large', 'Options Back applies both settings to preserved Arena');
      info.notify({ category: 'system', heading: 'TRANSITION TEST' }); info.update(0); info.update(220);
      game.scene.sleep('arena'); check(info.queue.active === null && info.queue.pending.length === 0, 'Leaving Arena clears visible and queued messages');
      game.scene.wake('arena');
      const oldInfo = info, oldRoot = info.root;
      arena.createRoundFromDefinition(arena.roundManager.currentDefinition());
      info = arena.hudInformation;
      check(oldInfo !== info && oldInfo.destroyed && !oldRoot.scene && oldInfo.queue.pending.length === 0, 'Encounter replacement retires the old notification owner');
      check(all(arena).filter(o => o.name === 'hud-information').length === 1, 'Replacement has exactly one notification service');
      report.profileId = SaveSystem.getActiveProfileSummary().id;
      SaveSystem.persist();
      arena.sys.sceneUpdate = originalUpdate; originalUpdate = null;
      game.scene.stop('arena'); await wait(100);
      check(info.destroyed && !info.root.scene, 'Scene shutdown releases notification root');
      check(Phaser.Display.Canvas.CanvasPool.pool.filter(e => e.parent?.scene === arena).length === 0, 'Shutdown releases every Arena Text canvas');
    } catch (error) { report.errors.push(String(error.stack ?? error)); }
    finally {
      if (originalUpdate && arena) arena.sys.sceneUpdate = originalUpdate;
      if (oldPads) Object.defineProperty(navigator, 'getGamepads', oldPads); else delete navigator.getGamepads;
      for (const key of ['options', 'arena']) if (game.scene.isActive(key) || game.scene.isPaused(key) || game.scene.isSleeping(key)) game.scene.stop(key);
      parent.style.width = parentStyle.width; parent.style.height = parentStyle.height;
      game.scale.resize(originalSize.width, originalSize.height); game.scale.refresh(); report.running = false;
    }
  })();
  return 'HUD information browser audit started';
})();
